<div align="center">
    <img src="recursos/img/logoitqv1.jpg" width="200">
</div>

**0.1 01MIAR - Estructuras de datos, +andas**

<p align="center">
  <img src="recursos/img/python_logo.png" width="200">
</p>

Kerly Pilco

**Fecha:** 29/06/2026

**Repositorio:** [Link del repositorio de GitHub]

(https://github.com/kelapilco/machine-1-2026-nocturno.git)

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.3'

**1. Operaciones en pandas**

**Busqueda**

In [4]:
rand_matrix = np.random.randint(6,size=(2,3))
frame = pd.DataFrame(rand_matrix , columns=list('ABC'))
display(frame)

   A  B  C
0  5  1  4
1  0  2  2

In [5]:
# buscando columnas (DataFrame como dic, busca en claves)
'A' in frame

True

In [6]:
# buscando valores
display(frame.isin([3,2])) # --> mask de respuesta (valores que son 3 o 2)

       A      B      C
0  False  False  False
1  False   True   True

In [7]:
# Contar el número de ocurrencias
print(frame.isin([4]).values.sum())
display(frame.isin([4])) #devuelve una mask con valores true si el elemento es 4
print(frame.isin([4]).values)
type(frame.isin([4]).values) # pandas es una capa alrededor de numpy

1

       A      B      C
0  False  False   True
1  False  False  False

[[False False  True]
 [False False False]]

numpy.ndarray

In [8]:
# Cuántos valores son >= 2
mask = frame >= 2
print(mask.values.sum())
display(mask)

4

       A      B     C
0   True  False  True
1  False   True  True

In [9]:
from random import shuffle
rand_matrix = np.random.randint(20,size=(5,4))
indices = list(range(5))
shuffle(indices) # mezcla indices
frame = pd.DataFrame(rand_matrix , columns=list('DACB'), index=indices)
display(frame)

   D   A   C   B
2  0   9   4  13
1  4   2  12   8
0  4   0   6   4
4  0  13   6  16
3  8  12   9  17

In [10]:
# ordenar por índice
display(frame.sort_index(ascending=False))
display(frame)

   D   A   C   B
4  0  13   6  16
3  8  12   9  17
2  0   9   4  13
1  4   2  12   8
0  4   0   6   4

   D   A   C   B
2  0   9   4  13
1  4   2  12   8
0  4   0   6   4
4  0  13   6  16
3  8  12   9  17

In [11]:
 #ordenar por columna
display(frame.sort_index(axis=1, ascending=False))

   D   C   B   A
2  0   4  13   9
1  4  12   8   2
0  4   6   4   0
4  0   6  16  13
3  8   9  17  12

In [12]:
# ordenar filas por valor en columna
display(frame.sort_values(by='A', ascending=True))

   D   A   C   B
0  4   0   6   4
1  4   2  12   8
2  0   9   4  13
3  8  12   9  17
4  0  13   6  16

In [13]:
# ordenar columnas por valor en fila
display(frame.sort_values(by=1, axis=1, ascending=True))

    A  D   B   C
2   9  0  13   4
1   2  4   8  12
0   0  4   4   6
4  13  0  16   6
3  12  8  17   9

In [14]:
# ordenar por valor en columna y guardar cambios
frame.sort_values(by='A', ascending=False, inplace=True)
display(frame)

   D   A   C   B
4  0  13   6  16
3  8  12   9  17
2  0   9   4  13
1  4   2  12   8
0  4   0   6   4

**Ranking**

. Construir un ranking de valor

In [15]:
display(frame)

   D   A   C   B
4  0  13   6  16
3  8  12   9  17
2  0   9   4  13
1  4   2  12   8
0  4   0   6   4

In [16]:
display(frame.rank(method="max", axis=1))

     D    A    C    B
4  1.0  3.0  2.0  4.0
3  1.0  3.0  2.0  4.0
2  1.0  3.0  2.0  4.0
1  2.0  1.0  4.0  3.0
0  3.0  1.0  4.0  3.0

In [18]:
# Imprimir, uno a uno, los valores de la columna 'C' de mayor a menor
for x in frame.sort_values(by='C', ascending=False)['C'].values:
     print(x)

12
9
6
6
4

**2 Operaciones**

Operaciones matemáticas entre objetos

In [19]:
matrixA = np.random.randint(100,size=(4,4))
matrixB = np.random.randint(100,size=(4,4))
frameA = pd.DataFrame(matrixA)
frameB = pd.DataFrame(matrixB)
display(frameA)
display(frameB)

    0   1   2   3
0  22  20  53  25
1  47  22  72  91
2  98  24  88  55
3  54  52  75  61

    0   1   2   3
0  46  26   2  96
1  18  23  27  29
2  36  52  39  89
3  70   8  10  67

In [20]:
 # a través de métodos u operadores
display(frameA + frameB == frameA.add(frameB))
display(frameA + frameB)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

     0   1    2    3
0   68  46   55  121
1   65  45   99  120
2  134  76  127  144
3  124  60   85  128

In [21]:
display(frameB - frameA == frameB.sub(frameA))
display(frameB - frameA)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

    0   1   2   3
0  24   6 -51  71
1 -29   1 -45 -62
2 -62  28 -49  34
3  16 -44 -65   6

In [22]:
# si los frames no son iguales, valor por defecto NaN
frameC = pd.DataFrame(np.random.randint(100,size=(3,3)))
display(frameA)
display(frameC)
display(frameC + frameA)

    0   1   2   3
0  22  20  53  25
1  47  22  72  91
2  98  24  88  55
3  54  52  75  61

    0   1   2
0  29  71  20
1  67  67  76
2  90  18  44

       0     1      2   3
0   51.0  91.0   73.0 NaN
1  114.0  89.0  148.0 NaN
2  188.0  42.0  132.0 NaN
3    NaN   NaN    NaN NaN

In [23]:
# se puede especificar el valor por defecto con el argumento fill_value
display(frameA.add(frameC, fill_value=0))

       0     1      2     3
0   51.0  91.0   73.0  25.0
1  114.0  89.0  148.0  91.0
2  188.0  42.0  132.0  55.0
3   54.0  52.0   75.0  61.0

Operadores aritméticos solo válidos en elementos aceptables

In [24]:
frameD = pd.DataFrame({0: ['a','b'],1:['d','f']})
display(frameD)
frameA - frameD

   0  1
0  a  d
1  b  f

TypeError: unsupported operand type(s) for -: 'int' and 'str'

Operaciones entre Series y DataFrames

In [25]:
rand_matrix = np.random.randint(10, size=(3, 4))
df = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(df)
display(df.iloc[0])
display(type(df.iloc[0]))
# uso común, averiguar la diferencia entre una fila y el resto
display(df - df.iloc[0])
display(df.sub(df.iloc[0], axis=1))
# Por columnas cómo se restaría
display(df.sub(df['A'], axis=0))

   A  B  C  D
0  3  5  5  4
1  0  6  7  4
2  1  9  9  3

A    3
B    5
C    5
D    4
Name: 0, dtype: int32

pandas.Series

   A  B  C  D
0  0  0  0  0
1 -3  1  2  0
2 -2  4  4 -1

   A  B  C  D
0  0  0  0  0
1 -3  1  2  0
2 -2  4  4 -1

   A  B  C  D
0  0  2  2  1
1  0  6  7  4
2  0  8  8  2

pandas se basa en NumPy, np operadores binarios y unarios son aceptables

| Tipo | Operación | Descripción |
|:----:|:---------:|-------------|
| Unario | `abs` | Valor absoluto de cada elemento. |
| Unario | `sqrt` | Raíz cuadrada de cada elemento. |
| Unario | `exp` | \(e^x\), siendo *x* cada elemento. |
| Unario | `log`, `log10`, `log2` | Logaritmos en distintas bases de cada elemento. |
| Unario | `sign` | Retorna el signo de cada elemento (-1 para negativo, 0 para cero y 1 para positivo). |
| Unario | `ceil` | Redondea cada elemento hacia arriba. |
| Unario | `floor` | Redondea cada elemento hacia abajo. |
| Unario | `isnan` | Retorna si cada elemento es `NaN`. |
| Unario | `cos`, `sin`, `tan` | Operaciones trigonométricas de cada elemento. |
| Unario | `arccos`, `arcsin`, `arctan` | Inversas de las operaciones trigonométricas de cada elemento. |
| Binario | `add` | Suma de dos arrays. |
| Binario | `subtract` | Resta de dos arrays. |
| Binario | `multiply` | Multiplicación de dos arrays. |
| Binario | `divide` | División de dos arrays. |
| Binario | `maximum`, `minimum` | Retorna el valor máximo o mínimo de cada pareja de elementos. |
| Binario | `equal`, `not_equal` | Compara si cada pareja de elementos es igual o diferente. |
| Binario | `greater`, `greater_equal`, `less`, `less_equal` | Compara cada pareja de elementos usando `>`, `>=`, `<` y `<=`, respectivamente. |

Aplicación de funciones a medida con lambda

In [26]:
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)
print(frame.apply(lambda x : x.max() - x.min(), axis = 1)) # diferencia por␣columna

   A  B  C  D
0  5  6  0  2
1  7  9  7  0
2  1  6  7  1

0    6
1    9
2    6
dtype: int32

In [28]:
def max_min(x):
  return x.max() - x.min()
print(frame.apply(max_min, axis = 0)) # diferencia por columna

A    6
B    3
C    7
D    2
dtype: int32

In [29]:
# diferencia entre min y max por fila (no columna)
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)
print(frame.apply(lambda x : x.max() - x.min(), axis = 1)) # diferencia por fila

   A  B  C  D
0  3  5  3  3
1  3  2  8  6
2  1  3  5  0

0    2
1    6
2    5
dtype: int32

**3 Estadística descriptiva**

• Análisis preliminar de los datos

• Para Series y DataFrame

| Operación | Descripción |
|-----------|-------------|
| `count` | Número de valores no NaN. |
| `describe` | Conjunto de estadísticas sumarias. |
| `min`, `max` | Valores mínimo y máximo. |
| `argmin`, `argmax` | Índices posicionales del valor mínimo y máximo. |
| `idxmin`, `idxmax` | Índices semánticos del valor mínimo y máximo. |
| `sum` | Suma de los elementos. |
| `mean` | Media de los elementos. |
| `median` | Mediana de los elementos. |
| `mad` | Desviación absoluta media del valor medio. |
| `var` | Varianza de los elementos. |
| `std` | Desviación estándar de los elementos. |
| `cumsum` | Suma acumulada de los elementos. |
| `diff` | Diferencia aritmética entre elementos consecutivos. |

In [30]:
diccionario = { "nombre" : ["Marisa","Laura","Manuel", "Carlos"], "edad" :[34,34,11, 30],
"puntos" : [98,12,98,np.nan], "genero": ["F", "F", "M", "M"] }
frame = pd.DataFrame(diccionario)
display(frame)
display(frame.describe()) # datos generales de elementos

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

            edad     puntos
count   4.000000   3.000000
mean   27.250000  69.333333
std    10.996211  49.652123
min    11.000000  12.000000
25%    25.250000  55.000000
50%    32.000000  98.000000
75%    34.000000  98.000000
max    34.000000  98.000000

In [31]:
# operadores básicos
print(frame.sum())
display(frame)
print(frame.sum(axis=1, numeric_only=True))

nombre    MarisaLauraManuelCarlos
edad                          109
puntos                      208.0
genero                       FFMM
dtype: object

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

0    132.0
1     46.0
2    109.0
3     30.0
dtype: float64

In [32]:
frame.mean(numeric_only=True)

edad      27.250000
puntos    69.333333
dtype: float64

In [33]:
frame.cumsum()

                    nombre  edad  puntos genero
0                   Marisa    34    98.0      F
1              MarisaLaura    68   110.0     FF
2        MarisaLauraManuel    79   208.0    FFM
3  MarisaLauraManuelCarlos   109     NaN   FFMM

In [34]:
frame.count(axis=1)

0    4
1    4
2    4
3    3
dtype: int64

In [35]:
 print(frame['edad'].std())

10.996211468804457

In [36]:
frame['edad'].idxmax()

0

In [37]:
 # frame con las filas con los valores maximos de una columna
print(frame['puntos'].max())
display(frame[frame['puntos'] == frame['puntos'].max()])

98.0

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
2  Manuel    11    98.0      M

In [38]:
frame["ranking"] = frame["puntos"].rank(method='max')

In [39]:
 display(frame)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

**3.1 Agregaciones**

In [40]:
display(frame)
df = frame.groupby('genero').count()
display(df)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

        nombre  edad  puntos  ranking
genero
F            2     2       2        2
M            2     2       1        1

In [41]:
# si es Nan descarta la fila
df = frame.groupby('puntos').count()
display(df)

        nombre  edad  genero  ranking
puntos
12.0         1     1       1        1
98.0         2     2       2        2

In [42]:
display(frame.groupby('genero').mean(numeric_only=True))

        edad  puntos  ranking
genero
F       34.0    55.0      2.0
M       20.5    98.0      3.0

In [43]:
display(frame.groupby('genero').max())

        nombre  edad  puntos  ranking
genero
F       Marisa    34    98.0      3.0
M       Manuel    30    98.0      3.0

In [44]:
# funciones de agregación de varias columnas para obtener distintos estadísticos
display(frame.groupby('genero')[['edad', 'puntos']].aggregate(['min', 'mean','max']))

       edad           puntos
        min  mean max    min  mean   max
genero
F        34  34.0  34   12.0  55.0  98.0
M        11  20.5  30   98.0  98.0  98.0

In [46]:
# Filtrado de los datos en el que el conjunto no supera una media determinada
def media(x):
  return x["edad"].mean() > 30
display(frame)
frame.groupby('genero').filter(media)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0

**3.2 Correlaciones**

pandas incluye métodos para analizar correlaciones - Relación matemática entre dos variables (-1 negativamente relacionadas, 1 positivamente relacionadas, 0 sin relación) - obj.corr(obj2) –
> medida de correlación entre los datos de ambos objetos - https://blogs.oracle.com/ai-anddatascience/post/introduction-to-correlation
> 
**3.2.1 Ejemplo Fuel efficiency**

• https://archive.ics.uci.edu/ml/datasets/Auto+MPG

In [48]:
import pandas as pd
path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
mpg_data = pd.read_csv(path, sep='\s+', header=None,
  names = ['mpg', 'cilindros', 'desplazamiento','potencia',
  'peso', 'aceleracion', 'año', 'origen', 'nombre'],
  na_values='?', engine='c')

In [49]:
display(mpg_data.sample(5))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
305,28.4,4,151.0,90.0,2670.0,16.0,79,1,buick skylark limited
391,36.0,4,135.0,84.0,2370.0,13.0,82,1,dodge charger 2.2
345,35.1,4,81.0,60.0,1760.0,16.1,81,3,honda civic 1300
191,22.0,6,225.0,100.0,3233.0,15.4,76,1,plymouth valiant
5,15.0,8,429.0,198.0,4341.0,10.0,70,1,ford galaxie 500

In [50]:
display(mpg_data.describe(include='all'))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000,NaN

In [51]:
display(mpg_data.describe(include='all'))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000,NaN

3.2.2 Correlaciones entre valores

In [52]:
 mpg_data['mpg'].corr(mpg_data['peso']) # + mpg = - peso

np.float64(-0.8317409332443351)

In [53]:
mpg_data['peso'].corr(mpg_data['aceleracion']) # + peso = - aceleracion

np.float64(-0.4174573199403932)

3.2.3 Correlaciones entre todos los valores

In [55]:
mpg_data.corr(numeric_only=True)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289,0.579267,0.563450
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419,-0.348746,-0.562543
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684,-0.370164,-0.609409
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196,-0.416361,-0.455171
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457,-0.306564,-0.581024
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000,0.288137,0.205873
año,0.579267,-0.348746,-0.370164,-0.416361,-0.306564,0.288137,1.000000,0.180662
origen,0.563450,-0.562543,-0.609409,-0.455171,-0.581024,0.205873,0.180662,1.000000

In [56]:
#año y origen no parecen correlacionables
#eliminar columnas de la correlacion
corr_data = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
display(corr_data)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000

In [57]:
 # representación gráfica matplotlib
import matplotlib.pyplot as plt

In [58]:
# representación gráfica
corr_data.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1)

In [59]:
# correlación más negativa
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmin()

mpg                   peso
cilindros              mpg
desplazamiento         mpg
potencia               mpg
peso                   mpg
aceleracion       potencia
dtype: str

In [61]:
# correlación más positiva
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmax() 
#consigo misma....

mpg                          mpg
cilindros              cilindros
desplazamiento    desplazamiento
potencia                potencia
peso                        peso
aceleracion          aceleracion
dtype: str

In [62]:
# tabla similar con las correlaciones más positivas (evitar parejas del mismo␣valor)
positive_corr = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
np.fill_diagonal(positive_corr.values, 0)
display(positive_corr)
positive_corr.idxmax()

ValueError: underlying array is read-only

In [63]:
positive_corr.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1,vmin=-1.0, vmax=1.0)

**3.3 Ejercicios**

• Ejercicios para practicar Pandas: https://github.com/ajcr/100-pandaspuzzles/blob/master/100-pandas-puzzles.ipynb

In [64]:
import pandas as pd

print(pd.__version__)

3.0.3

In [65]:
import pandas as pd

data = [2, 4, 6, 8, 10]

serie = pd.Series(data)

print(serie)

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [66]:
import pandas as pd

serie = pd.Series([2,4,6,8,10])

df = serie.to_frame(name='Numeros')

print(df)

   Numeros
0        2
1        4
2        6
3        8
4       10

In [69]:
import pandas as pd

s1 = pd.Series(['A','B','C','D'])
s2 = pd.Series([10,20,30,40])

df = pd.DataFrame({
    'Letras': s1,
    'Valores': s2
})

print(df)

  Letras  Valores
0      A       10
1      B       20
2      C       30
3      D       40

In [68]:
import pandas as pd

serie = pd.Series(
    [100,200,300],
    index=['x','y','z']
)

print(serie)

x    100
y    200
z    300
dtype: int64

In [70]:
import pandas as pd

serie = pd.Series(range(1,11))

print(serie.head())

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [71]:
import pandas as pd

serie = pd.Series(range(1,11))

print(serie.tail())

5     6
6     7
7     8
8     9
9    10
dtype: int64

In [72]:
import pandas as pd

df = pd.DataFrame({
    'A':[1,2,3]
})

df.rename(columns={'A':'Numero'}, inplace=True)

print(df)

   Numero
0       1
1       2
2       3

In [73]:
import pandas as pd

df = pd.DataFrame({
    'Nombre':['Ana','Luis','Carlos'],
    'Edad':[20,22,21]
})

print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  3 non-null      str
 1   Edad    3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes
None

In [74]:
import pandas as pd

df = pd.DataFrame({
    'Edad':[18,20,22,24,26]
})

print(df.describe())

            Edad
count   5.000000
mean   22.000000
std     3.162278
min    18.000000
25%    20.000000
50%    22.000000
75%    24.000000
max    26.000000

In [75]:
import pandas as pd
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

serie = pd.Series(arr)

print(serie)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [76]:
import pandas as pd

serie = pd.Series(
    [100, 200, 300],
    index=["a", "b", "c"]
)

print(serie)

a    100
b    200
c    300
dtype: int64

In [77]:
import pandas as pd

serie = pd.Series(
    [5, 10, 15],
    index=["x", "y", "z"]
)

print(serie["y"])

10

In [78]:
import pandas as pd

serie = pd.Series([2, 8, 15, 20, 5])

resultado = serie[serie > 10]

print(resultado)

2    15
3    20
dtype: int64

In [79]:
import pandas as pd

serie = pd.Series([10,20,30,40])

serie[2] = 100

print(serie)

0     10
1     20
2    100
3     40
dtype: int64

In [80]:
import pandas as pd

serie = pd.Series([10,20,30])

serie.loc[3] = 40

print(serie)

0    10
1    20
2    30
3    40
dtype: int64

In [81]:
import pandas as pd

serie = pd.Series([10,20,30,40])

serie = serie.drop(1)

print(serie)

0    10
2    30
3    40
dtype: int64

In [82]:
import pandas as pd

serie = pd.Series([30,10,50,20])

print(serie.sort_values())

1    10
3    20
0    30
2    50
dtype: int64

In [83]:
import pandas as pd

serie = pd.Series([1,2,2,3,3,3,4])

print(serie.unique())

[1 2 3 4]

In [84]:
import pandas as pd

serie = pd.Series([1,2,2,3,3,3,4])

print(serie.value_counts())

3    3
2    2
1    1
4    1
Name: count, dtype: int64